// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_Q3ZYoUPEgVSUAYO7LFig2Jugux2xhQ',
    appId: '1:765983182567:web:57bb90b9f5cfcaead2dc42',
    messagingSenderId: '765983182567',
    projectId: 'food-donation-tracker-dea3f',
    authDomain: 'food-donation-tracker-dea3f.firebaseapp.com',
    databaseURL: 'https://food-donation-tracker-dea3f-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-tracker-dea3f.firebasestorage.app',
    measurementId: 'G-W7E6LT76NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjFI7YnFq07sMQ1NMxqAQJNVAv8ou9kxc',
    appId: '1:765983182567:android:58e73f981e2b073dd2dc42',
    messagingSenderId: '765983182567',
    projectId: 'food-donation-tracker-dea3f',
    databaseURL: 'https://food-donation-tracker-dea3f-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-tracker-dea3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRdHI0ghOQVyCTmvhaC55gm6SBKA0yXMc',
    appId: '1:765983182567:ios:d7758b8afa93ccacd2dc42',
    messagingSenderId: '765983182567',
    projectId: 'food-donation-tracker-dea3f',
    databaseURL: 'https://food-donation-tracker-dea3f-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-tracker-dea3f.firebasestorage.app',
    iosBundleId: 'com.example.foodlink.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRdHI0ghOQVyCTmvhaC55gm6SBKA0yXMc',
    appId: '1:765983182567:ios:d7758b8afa93ccacd2dc42',
    messagingSenderId: '765983182567',
    projectId: 'food-donation-tracker-dea3f',
    databaseURL: 'https://food-donation-tracker-dea3f-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-tracker-dea3f.firebasestorage.app',
    iosBundleId: 'com.example.foodlink.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_Q3ZYoUPEgVSUAYO7LFig2Jugux2xhQ',
    appId: '1:765983182567:web:a336c64d265ed31fd2dc42',
    messagingSenderId: '765983182567',
    projectId: 'food-donation-tracker-dea3f',
    authDomain: 'food-donation-tracker-dea3f.firebaseapp.com',
    databaseURL: 'https://food-donation-tracker-dea3f-default-rtdb.firebaseio.com',
    storageBucket: 'food-donation-tracker-dea3f.firebasestorage.app',
    measurementId: 'G-WYHH6J8P23',
  );
}
